# Generated by Django 4.2.6 on 2024-01-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('datum_projekta', models.DateField()),
                ('mjesto', models.CharField(default=' ', max_length=30)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volonter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('godine', models.IntegerField(default=0)),
                ('volonter_prije', models.BooleanField(default=True)),
                ('dogadaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Volonterska_skupina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30)),
                ('volonteri', models.ManyToManyField(related_name='volonterske_skupine', to='main.volonter')),
            ],
        ),
    ]
