# Generated by Django 4.2.6 on 2024-01-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volonter',
            old_name='dogadaj',
            new_name='projekt',
        ),
    ]
